# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/mdisk/FaceProj/swap_ui/ImgTool/face_reenact.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.uwidget = QtWidgets.QWidget(self.centralwidget)
        self.uwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.uwidget.sizePolicy().hasHeightForWidth())
        self.uwidget.setSizePolicy(sizePolicy)
        self.uwidget.setMinimumSize(QtCore.QSize(300, 60))
        self.uwidget.setMaximumSize(QtCore.QSize(16777215, 50000))
        self.uwidget.setStyleSheet("background: #dddddd")
        self.uwidget.setObjectName("uwidget")
        self.gridLayout.addWidget(self.uwidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Tools = QtWidgets.QMenu(self.menubar)
        self.menu_Tools.setObjectName("menu_Tools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Quit = QtWidgets.QAction(MainWindow)
        self.action_Quit.setObjectName("action_Quit")
        self.action_Source_Images = QtWidgets.QAction(MainWindow)
        self.action_Source_Images.setObjectName("action_Source_Images")
        self.action_Moab = QtWidgets.QAction(MainWindow)
        self.action_Moab.setObjectName("action_Moab")
        self.actionFilm = QtWidgets.QAction(MainWindow)
        self.actionFilm.setObjectName("actionFilm")
        self.action_Gpen = QtWidgets.QAction(MainWindow)
        self.action_Gpen.setObjectName("action_Gpen")
        self.menu_File.addAction(self.action_Quit)
        self.menu_Tools.addAction(self.action_Source_Images)
        self.menu_Tools.addAction(self.action_Moab)
        self.menu_Tools.addAction(self.actionFilm)
        self.menu_Tools.addAction(self.action_Gpen)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Tools.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Tools.setTitle(_translate("MainWindow", "&Tools"))
        self.action_Quit.setText(_translate("MainWindow", "&Quit"))
        self.action_Source_Images.setText(_translate("MainWindow", "&Source Images..."))
        self.action_Moab.setText(_translate("MainWindow", "&Moab"))
        self.actionFilm.setText(_translate("MainWindow", "F&ilm"))
        self.action_Gpen.setText(_translate("MainWindow", "&Gpen"))
